name: 'On Review'
on: issue_comment
jobs:
  pr_commented:
    name: 'PR comment'
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Policy Reviews
        run: |
          pip install slack_sdk
          python ./scripts/workflows/policy_review_workflow.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT: ${{ toJson(github.event) }}